#include "PCH.h"
#include "HotkeyManager.h"
#include "ItemEnumerator.h"
#include "PrismaBridge.h"
#include "Settings.h"

#include <spdlog/sinks/basic_file_sink.h>

namespace
{
    void OnSKSEMessage(SKSE::MessagingInterface::Message* msg)
    {
        if (!msg) return;
        switch (msg->type) {
            case SKSE::MessagingInterface::kPostLoad:
                Settings::Load();
                if (!PrismaBridge::Initialize()) {
                    logger::error("PrismaBridge::Initialize failed — menu won't work");
                }
                break;

            case SKSE::MessagingInterface::kDataLoaded:
                ItemEnumerator::Refresh();
                HotkeyManager::Install();
                logger::info("PrismaUIAddItemMenu: ready ({} items cached)",
                             ItemEnumerator::CacheSize());
                break;

            case SKSE::MessagingInterface::kPostLoadGame:
            case SKSE::MessagingInterface::kNewGame:
                ItemEnumerator::Refresh();
                Settings::ReloadIfChanged();
                break;

            default:
                break;
        }
    }
}

// SKSEPlugin_Version is auto-generated by add_commonlibsse_plugin in
// CMakeLists.txt — defining it here too produces LNK2005. Name, author,
// version, and "I'm address-library-only / no struct dependencies" all
// flow through the macro's NAME/AUTHOR/VERSION/USE_ADDRESS_LIBRARY args.

extern "C" __declspec(dllexport) bool SKSEPlugin_Load(const SKSE::LoadInterface* skse)
{
    // false → skip auto logger init; we set up our own file sink under the
    // SKSE standard log directory so users find it next to other plugins.
    SKSE::Init(skse, false);

    auto path = logger::log_directory();
    if (!path) return false;
    *path /= "PrismaUIAddItemMenu.log";

    auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(path->string(), true);
    auto log = std::make_shared<spdlog::logger>("global", std::move(sink));
    log->set_level(spdlog::level::info);
    log->flush_on(spdlog::level::info);
    spdlog::set_default_logger(std::move(log));
    spdlog::set_pattern("[%H:%M:%S.%e] [%^%l%$] %v");

    logger::info("PrismaUIAddItemMenu loading (build {} {})", __DATE__, __TIME__);
    logger::info("Running on Skyrim v{}", REL::Module::get().version().string());

    auto* msg = SKSE::GetMessagingInterface();
    if (!msg || !msg->RegisterListener(OnSKSEMessage)) {
        logger::error("Failed to register SKSE message listener");
        return false;
    }

    return true;
}
